theme: jekyll-theme-cayman
title: LaTe + LaMP home page
description: Home page for LaTe, the flexible Latency Tester, and LaMP, a custom Latency Measurement Protocol
show_downloads: true

github:
  zip_url: https://github.com/francescoraves483/LaMP_LaTe/archive/v0.1.1-beta.zip
  tar_url: https://github.com/francescoraves483/LaMP_LaTe/archive/v0.1.1-beta.tar.gz
  owner_name: Politecnico di Torino
  lampspec_url: https://francescoraves483.github.io/LaMP_LaTe/LaMP/LaMP_specifications_rev1.0.pdf